Add sanity checks to build scripts

diff --git a/cmbuild b/cmbuild
--- a/cmbuild
+++ b/cmbuild
@@ -21,6 +21,18 @@ case $# in
 esac
 
 #
+# sanity check
+#
+if [ ! -x /usr/bin/cmake ]; then
+    echo "ERROR: cmake not installed"
+    exit 1
+fi
+if [ ! -x ${GMAKE} ]; then
+    echo "ERROR: gmake not installed"
+    exit 1
+fi
+
+#
 # if a dual 32- and 64-bit build is desired, specify -64 *first*
 # +64 means just do the 64-bit (useful for testing it in isolation)
 # note that +64 will wipe the 32-bit directory
diff --git a/dobuild b/dobuild
--- a/dobuild
+++ b/dobuild
@@ -20,6 +20,14 @@ case $# in
 esac
 
 #
+# sanity check
+#
+if [ ! -x ${GMAKE} ]; then
+    echo "ERROR: gmake not installed"
+    exit 1
+fi
+
+#
 # if a dual 32- and 64-bit build is desired, specify -64 *first*
 # +64 means just do the 64-bit (useful for testing it in isolation,
 # or for building 64-bit and 32-bit with different flags)
diff --git a/mesonbuild b/mesonbuild
--- a/mesonbuild
+++ b/mesonbuild
@@ -20,6 +20,18 @@ case $# in
 esac
 
 #
+# sanity check
+#
+if [ ! -x /usr/bin/ninja ]; then
+    echo "ERROR: ninja not installed"
+    exit 1
+fi
+if [ ! -x /usr/bin/meson ]; then
+    echo "ERROR: meson not installed"
+    exit 1
+fi
+
+#
 # if a dual 32- and 64-bit build is desired, specify -64 *first*
 # +64 means just do the 64-bit (useful for testing it in isolation)
 # note that +64 will wipe the 32-bit directory
