Centralize errors in genpkg and create_pkg

diff --git a/create_pkg b/create_pkg
--- a/create_pkg
+++ b/create_pkg
@@ -36,6 +36,11 @@ case $# in
 	;;
 esac
 
+bail() {
+    echo "ERROR: $1"
+    exit 1
+}
+
 #
 # Default locations
 #
@@ -47,20 +52,17 @@ MYARCH=$(uname -p)
 # sanity check
 #
 if [ ! -d $BUILD ]; then
-   echo "ERROR: unable to find build directory $BUILD"
-   exit 1
+   bail "unable to find build directory $BUILD"
 fi
 if [ ! -d $BROOT ]; then
    mkdir -p ${BROOT}
 fi
 if [ ! -d $BROOT ]; then
-   echo "ERROR: unable to find temporary directory $BROOT"
-   exit 1
+   bail "unable to find temporary directory $BROOT"
 fi
 if [ ! -f ${BUILD}/${PKGNAME}/pkginfo ]; then
-   echo "ERROR: missing package data"
    echo "Please create ${BUILD}/${PKGNAME}/pkginfo"
-   exit 1
+   bail "missing package data"
 fi
 
 #
@@ -177,7 +179,7 @@ EOF
 }
 
 PKGVER=`/usr/bin/grep '^VERSION=' ${BUILD}/${PKGNAME}/pkginfo | /usr/bin/awk -F= '{print $2}' | /usr/bin/sed 's:"::g'`
-cd $BDIR
+cd $BDIR || bail "no directory to package"
 # copy packaging files from archive
 cp ${BUILD}/${PKGNAME}/pkginfo .
 if [ -f ${BUILD}/${PKGNAME}/pkginfo.arch ]; then
diff --git a/genpkg b/genpkg
--- a/genpkg
+++ b/genpkg
@@ -55,6 +55,11 @@ case $# in
 	;;
 esac
 
+bail() {
+    echo "ERROR: $1"
+    exit 1
+}
+
 #
 # Default locations
 #
@@ -67,24 +72,20 @@ GMAKE="/usr/bin/gmake"
 # sanity check
 #
 if [ ! -d $BUILD ]; then
-   echo "ERROR: unable to find build directory $BUILD"
-   exit 1
+   bail "unable to find build directory $BUILD"
 fi
 if [ ! -d $BROOT ]; then
    mkdir -p ${BROOT}
 fi
 if [ ! -d $BROOT ]; then
-   echo "ERROR: unable to find temporary directory $BROOT"
-   exit 1
+   bail "unable to find temporary directory $BROOT"
 fi
 if [ ! -x $GMAKE ]; then
-   echo "ERROR: unable to find $GMAKE"
-   exit 1
+   bail "unable to find $GMAKE"
 fi
 if [ ! -f ${BUILD}/${PKGNAME}/pkginfo ]; then
-   echo "ERROR: missing package data"
    echo "Please create ${BUILD}/${PKGNAME}/pkginfo"
-   exit 1
+   bail "missing package data"
 fi
 
 #
