create-signatures should be driven by the catalog

diff --git a/create-signatures b/create-signatures
--- a/create-signatures
+++ b/create-signatures
@@ -9,27 +9,29 @@ builtin echo
 PKGDIR="../pkgs"
 case $# in
 1)
-	PKGDIR=$1
+	PKGDIR="$1"
 	;;
 esac
 
-if [ ! -f ${HOME}/Tribblix/Sign.phrase ]; then
+if [ ! -f "${HOME}/Tribblix/Sign.phrase" ]; then
     echo "Missing passphrase, must sign packages manually"
     exit 1
 fi
 
-for PKGI in */pkginfo
+if [ ! -f "${PKGDIR}/catalog" ]; then
+    echo "Missing catalog"
+    exit 1
+fi
+
+awk -F'|' '{print $1,$2}' "${PKGDIR}/catalog" | while read -r PKG PKGVERS
 do
-  PKG=${PKGI%/*}
-  PKGVERS=`awk -F= '{if ($1 == "VERSION") print $2}' $PKGI`
-  PKGVERS=${PKGVERS//\"/}
-  if [ -f ${PKGDIR}/${PKG}.${PKGVERS}.zap ]; then
-    if [ ! -f ${PKGDIR}/${PKG}.${PKGVERS}.zap.sig ]; then
+  if [ -f "${PKGDIR}/${PKG}.${PKGVERS}.zap" ]; then
+    if [ ! -f "${PKGDIR}/${PKG}.${PKGVERS}.zap.sig" ]; then
 	echo ""
-	echo "Signing package ${PKG}.${PKGVERS}."
+	echo "Signing package ${PKG}.${PKGVERS}"
 	echo ""
-	gpg --detach-sign --no-secmem-warning --passphrase-file ${HOME}/Tribblix/Sign.phrase ${PKGDIR}/${PKG}.${PKGVERS}.zap
-	if [ -f ${PKGDIR}/${PKG}.${PKGVERS}.zap.sig ]; then
+	gpg --detach-sign --no-secmem-warning --passphrase-file "${HOME}/Tribblix/Sign.phrase" "${PKGDIR}/${PKG}.${PKGVERS}.zap"
+	if [ -f "${PKGDIR}/${PKG}.${PKGVERS}.zap.sig" ]; then
 	    echo "Package signed successfully."
 	    echo ""
 	fi
