Prevent build scripts from running in a git repo and messing it up

diff --git a/dobuild b/dobuild
--- a/dobuild
+++ b/dobuild
@@ -28,6 +28,14 @@ if [ ! -x ${GMAKE} ]; then
 fi
 
 #
+# sanity check to avoid messing up a repo
+#
+if [ -d .git ]; then
+    echo "ERROR: cannot run in a git repo"
+    exit 1
+fi
+     
+#
 # if a dual 32- and 64-bit build is desired, specify -64 *first*
 # +64 means just do the 64-bit (useful for testing it in isolation,
 # or for building 64-bit and 32-bit with different flags)
diff --git a/pkg_gem b/pkg_gem
--- a/pkg_gem
+++ b/pkg_gem
@@ -23,6 +23,14 @@ case $# in
 esac
 
 #
+# sanity check to avoid messing up a repo
+#
+if [ -d .git ]; then
+    echo "ERROR: cannot run in a git repo"
+    exit 1
+fi
+     
+#
 # Default locations
 #
 THOME=${THOME:-/packages/localsrc/Tribblix}
diff --git a/pkg_setup_py b/pkg_setup_py
--- a/pkg_setup_py
+++ b/pkg_setup_py
@@ -41,6 +41,14 @@ if [ ! -f ${BUILD}/${PKGNAME}/pkginfo ]; then
    echo "Please create ${BUILD}/${PKGNAME}/pkginfo"
    exit 1
 fi
+
+#
+# sanity check to avoid messing up a repo
+#
+if [ -d .git ]; then
+    echo "ERROR: cannot run in a git repo"
+    exit 1
+fi
      
 if [ ! -d $BROOT ]; then
     mkdir -p $BROOT
diff --git a/pkg_tarball b/pkg_tarball
--- a/pkg_tarball
+++ b/pkg_tarball
@@ -48,6 +48,14 @@ if [ ! -f ${BUILD}/${PKGNAME}/pkginfo ]; then
 fi
 
 #
+# sanity check to avoid messing up a repo
+#
+if [ -d .git ]; then
+    echo "ERROR: cannot run in a git repo"
+    exit 1
+fi
+     
+#
 # define and create working location
 #
 BDIR="${BROOT}/pkg.$$"
