Use getopts in pkg_wheel

diff --git a/pkg_wheel b/pkg_wheel
--- a/pkg_wheel
+++ b/pkg_wheel
@@ -31,13 +31,23 @@ export TZ
 # wheel (see pkg_pep518 for one that creates the wheel from source)
 #
 
-case $1 in
-    -v)
-	SPYVER=$2
-	shift
-	shift
-	;;
-esac
+#
+# Arguments
+# -v - specify version of python (for packages that don't embed the python
+#      version in the package name)
+#
+while getopts "v:" opt; do
+    case $opt in
+	v)
+	    SPYVER="$OPTARG"
+	    ;;
+	*)
+            echo "ERROR: invalid option $OPTARG"
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND-1))
 
 case $# in
 0|1)
