Teach pkg_setup_py to understand -gnu

diff --git a/pkg_setup_py b/pkg_setup_py
--- a/pkg_setup_py
+++ b/pkg_setup_py
@@ -30,13 +30,27 @@ export TZ
 # package one or more python project(s) that use the old setup.py mechanism
 #
 
+while [[ $# -gt 0 ]]; do
 case $1 in
     -v)
 	SPYVER=$2
 	shift
 	shift
 	;;
+    -gnu)
+	PATH=/usr/gnu/bin:$PATH
+	export PATH
+	shift
+	;;
+    -*)
+	echo "ERROR: invalid option $1"
+	exit 1
+	;;
+    *)
+	break
+	;;
 esac
+done
 
 case $# in
 0|1)
