Fix fontconfig and smf

diff --git a/TRIBsys-lib-fontconfig/fixit b/TRIBsys-lib-fontconfig/fixit
--- a/TRIBsys-lib-fontconfig/fixit
+++ b/TRIBsys-lib-fontconfig/fixit
@@ -1,3 +1,226 @@
 #!/bin/sh
 #
 rm -fr usr/share/doc
+
+#
+# reinstate the smf manifest and method script
+#
+mkdir -p lib/svc/method
+mkdir -p lib/svc/manifest/application/font
+
+cat > lib/svc/method/fc-cache <<EOF
+#!/bin/ksh
+#
+# Copyright (c) 2008, Oracle and/or its affiliates. All rights reserved.
+#
+# Permission is hereby granted, free of charge, to any person obtaining a
+# copy of this software and associated documentation files (the "Software"),
+# to deal in the Software without restriction, including without limitation
+# the rights to use, copy, modify, merge, publish, distribute, sublicense,
+# and/or sell copies of the Software, and to permit persons to whom the
+# Software is furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice (including the next
+# paragraph) shall be included in all copies or substantial portions of the
+# Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
+# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
+# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
+# DEALINGS IN THE SOFTWARE.
+#
+###########################################################################
+#
+#
+
+PATH=/usr/bin:/usr/sbin
+
+. /lib/svc/share/smf_include.sh
+
+USAGE="Usage: \$0 <method>"
+
+if [ \$# -ne 1 ] ; then
+    echo \$USAGE
+    exit 2
+fi
+
+METHOD=\$1
+
+case \$METHOD in
+    start)
+        # Continue with rest of script
+        ;;
+    -*)
+        echo \$USAGE
+        exit 2
+        ;;
+    *)
+        echo "Invalid method \$METHOD"
+        exit 2
+        ;;
+esac
+
+getprop() {
+    PROPVAL=""
+    svcprop -q -p \$1 application/font/fc-cache
+    if [ \$? -eq 0 ] ; then
+        PROPVAL=\$(svcprop -p $1 application/font/fc-cache)
+        if [ "\$PROPVAL" == "\"\"" ] ; then
+            PROPVAL=""
+        fi
+        return
+    fi
+    return
+}
+
+
+ARGS=""
+POSTCMD=""
+RETVAL=\$SMF_EXIT_OK
+
+getprop options/force_rebuild
+if [ "\$PROPVAL" = "true" ] ; then
+    ARGS="\$ARGS -f"
+    POSTCMD="svccfg -s application/font/fc-cache setprop options/force_rebuild=f
+alse"
+fi
+
+/usr/bin/fc-cache \$ARGS
+if [ \$? -ne 0 ] ; then
+    RETVAL=\$SMF_EXIT_MON_DEGRADE
+fi
+
+if [ "\$POSTCMD" != "" ] ; then
+    eval \$POSTCMD
+fi
+
+exit \$RETVAL
+
+EOF
+
+chmod 555 lib/svc/method/fc-cache
+
+cat > lib/svc/manifest/application/font/fc-cache.xml  <<EOF
+<?xml version="1.0"?>
+<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
+<!--
+    Copyright (c) 2004, 2010, Oracle and/or its affiliates. All rights reserved.
+
+    Permission is hereby granted, free of charge, to any person obtaining a
+    copy of this software and associated documentation files (the "Software"),
+    to deal in the Software without restriction, including without limitation
+    the rights to use, copy, modify, merge, publish, distribute, sublicense,
+    and/or sell copies of the Software, and to permit persons to whom the
+    Software is furnished to do so, subject to the following conditions:
+
+    The above copyright notice and this permission notice (including the next
+    paragraph) shall be included in all copies or substantial portions of the
+    Software.
+
+    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
+    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
+    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
+    DEALINGS IN THE SOFTWARE.
+
+
+    Service manifest for ensuring fontconfig caches are up to date.
+-->
+
+<service_bundle type='manifest' name='SUNWfontconfig-root:fc-cache'>
+
+<service
+        name='application/font/fc-cache'
+        type='service'
+        version='1'>
+
+        <create_default_instance enabled='true' />
+
+        <single_instance />
+
+        <!-- Need / & /usr filesystems mounted readable, 
+             /var/cache mounted read/write -->
+        <dependency
+                name='usr'
+                type='service'
+                grouping='require_all'
+                restart_on='none'>
+                <service_fmri value='svc:/system/filesystem/minimal' />
+        </dependency>
+
+        <dependency
+                name='config-file'
+                grouping='require_all'
+                restart_on='refresh'
+                type='path'>
+                <service_fmri value='file://localhost/etc/fonts/fonts.conf' />
+        </dependency>
+
+        <dependency
+                name='fc-cache'
+                grouping='require_all'
+                restart_on='none'
+                type='path'>
+                <service_fmri value='file://localhost/usr/bin/fc-cache' />
+        </dependency>
+
+        <exec_method
+                type='method'
+                name='start'
+                exec='/lib/svc/method/fc-cache %m'
+                timeout_seconds='3600'>
+                <method_context>
+                        <method_credential user='root' group='root' />
+                </method_context>
+        </exec_method>
+
+        <exec_method
+                type='method'
+                name='stop'
+                exec=':true'
+                timeout_seconds='60' />
+
+
+        <property_group name='startd' type='framework'>
+                <propval name='duration' type='astring'
+                        value='transient' />
+        </property_group>
+
+        <property_group name='general' type='framework'>
+                <!-- manage server state -->
+                <propval name='action_authorization' type='astring'
+                        value='solaris.smf.manage.font' />
+        </property_group>
+
+        <property_group name='options' type='application'>
+                <stability value='Unstable' />
+                <propval name='force_rebuild' type='boolean'
+                 value='false' />
+        </property_group>
+
+        <stability value='Evolving' />
+
+        <template>
+                <common_name>
+                        <loctext xml:lang='C'>FontConfig Cache Builder
+                                </loctext>
+                </common_name>
+
+                <documentation>
+                        <manpage
+                                title='fc-cache'
+                                section='1M'
+                                manpath='/usr/share/man' />
+                </documentation>
+        </template>
+</service>
+
+</service_bundle>
+EOF
+
+chmod 444 lib/svc/manifest/application/font/fc-cache.xml
